# Generated by Django 2.1.7 on 2019-05-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190518_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Reason_for_admission',
            new_name='reason_for_admission',
        ),
    ]
