# Generated by Django 2.1.7 on 2019-05-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190518_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='current_passport_photograph_of_the_mother',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
